# Generated by Django 3.1.3 on 2020-11-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealsApp', '0002_auto_20201123_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals_ID', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('destription', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='admins',
        ),
    ]
