# Generated by Django 3.1.3 on 2020-11-30 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mealsApp', '0003_auto_20201123_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='destription',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='meals_ID',
        ),
        migrations.AddField(
            model_name='meals',
            name='category',
            field=models.CharField(default='lunch', max_length=100),
        ),
        migrations.AddField(
            model_name='meals',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meals',
            name='instruction',
            field=models.CharField(default='nothing', max_length=500),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('amountUnit', models.CharField(default='', max_length=100)),
                ('meal', models.ManyToManyField(to='mealsApp.Meals')),
            ],
        ),
    ]
