# Generated by Django 3.1.3 on 2020-11-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealsApp', '0004_auto_20201130_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='dateAdded',
        ),
    ]
