# Generated by Django 3.1.3 on 2020-11-30 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mealsApp', '0005_remove_meals_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
