# Generated by Django 3.1.3 on 2020-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealsApp', '0006_meals_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
