# Generated by Django 3.1.3 on 2020-12-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealsApp', '0007_auto_20201130_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='meal',
            field=models.ManyToManyField(related_name='ing_list', to='mealsApp.Meals'),
        ),
    ]
