# Generated by Django 3.1.3 on 2020-12-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealsApp', '0008_auto_20201206_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='meal',
            field=models.ManyToManyField(related_name='ingredients_list', to='mealsApp.Meals'),
        ),
    ]
